name: 🔥 portal wearesosure deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: .
      ENVIRONMENT: production
      BASE_URL: https://portal.wearesosure.com
      PCA_WEBKEY: ZW92-JM79-DF38-PY85
      PHONE_LIST_URL: https://wearesosure.com/list-phones-make-model
      SITE_NAME: Portal SO-SURE
      FB_API_KEY: AIzaSyBqlaHylDfUCbPb4AaA_RdlG00tbTw4j6c
      FB_AUTH_DOMAIN: portal-wearesosure-production.firebaseapp.com
      FB_PROJECT_ID: portal-wearesosure-production
      FB_STORAGE_BUCKET: portal-wearesosure-production.appspot.com
      FB_MESSAGING_SENDER_ID: 638819074909
      FB_APP_ID: 1:638819074909:web:98c5bc00847702f905deb4
      FB_MEASUREMENT_ID: G-BJ8NN4LJ2T
      NUXT_PUBLIC_SITE_URL: http://localhost:3000
      NUXT_INDEXABLE: false
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.9
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate site
        run: pnpm generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTAL_WEARESOSURE_PRODUCTION }}'
          channelId: live
          projectId: portal-wearesosure-production