name: 🔥 portal wearesosure deploy to dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: .
      ENVIRONMENT: development
      BASE_URL: https://portal.dev.wearesosure.com
      PCA_WEBKEY: ZW92-JM79-DF38-PY85
      PHONE_LIST_URL: https://staging.wearesosure.com/list-phones-make-model
      SITE_NAME: Portal SO-SURE (DEV)
      FB_API_KEY: AIzaSyDDAyeTFaZN4mwVjShoHc7YAIs5C6-tIB8
      FB_AUTH_DOMAIN: portal-wearesosure-dev.firebaseapp.com
      FB_PROJECT_ID: portal-wearesosure-dev
      FB_STORAGE_BUCKET: portal-wearesosure-dev.appspot.com
      FB_MESSAGING_SENDER_ID: 841019334396
      FB_APP_ID: 1:841019334396:web:d3cf626209052c40328179
      FB_MEASUREMENT_ID: G-J581VD9VNP
      NUXT_PUBLIC_SITE_URL: http://localhost:3000
      NUXT_INDEXABLE: false
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.9
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate site
        run: pnpm generate
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTAL_WEARESOSURE_DEV }}'
          channelId: live
          projectId: portal-wearesosure-dev